default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: profile_development
  username: postgres
  password: 12365478aA

test:
  <<: *default
  database: profile_test
  username: postgres
  password: 12365478aA

production:
  <<: *default
  database: profile_production
  username: profile
  password: <%= ENV['PROFILE_DATABASE_PASSWORD'] %>
